shared:
    image: node:8
    steps:
      - echo: echo hi

jobs:
  compile-commit:
    requires: [~commit]
    
  test-cases-serial-1-commit:
    requires: [ ~commit]

  test-cases-serial-2-commit:
    requires: [~commit]

  test-cases-unittest-commit:
    requires: [~commit]

  component:
    requires: [test-cases-unittest-commit, test-cases-serial-2-commit, test-cases-serial-1-commit, compile-commit]
    
  certify-ci_prod:
    requires:
      - ~sd@10:deploy-ci_prod
