shared:
    image: node:8
    steps:
        - echo: echo hi
jobs:
  main:
    requires: [~pr, ~commit]
  sc:
    requires: [~sd@555:cd]
  sr:
    requires: [~sd@555:sdf]
  sy:
    requires: [~sd@555:yd]
  te:
    requires: [~sd@777:ted, ~sd@222:cd ]
  client:
    requires: [~sd@49:client-functional-test]
  server:
    requires: [~sd@49:docker]
  sc2:
    requires: [~sd@555:scft]
  ci:
    requires: [~sd@555:console-id]
  tp:
    requires: [~sd@333:functestserver-docker, ~sd@333:functest-script]
  b:
    requires: [~sd@555:bd]
