shared:
    image: node:8
    steps:
        - echo: echo hi

jobs:
    component:
        requires: [~commit, ~sd@8:component]

    component-batch:
        requires: [component]
        

    component-bulk:
        requires: [component]

    component-dfm:
        requires: [component]

    component-iws:
        requires: [component]

    component-syncer:
        requires: [component]

    component-yapee:
        requires: [component]
        
    component-all:
        requires: [component-yapee, component-syncer, component-iws, component-dfm, component-bulk, component-batch]
